import Mathlib.AlgebraicTopology.FundamentalGroupoid.FundamentalGroup
import Mathlib.CategoryTheory.Endomorphism
import Mathlib.CategoryTheory.Groupoid.FreeGroupoid
import Mathlib.Combinatorics.Quiver.Covering
import Mathlib.GroupTheory.FreeGroup.NielsenSchreier
import Mathlib.Topology.Constructions

open Set Function
open CategoryTheory CategoryTheory.SingleObj Quiver FreeGroup
open unitInterval

noncomputable section

universe u

namespace FiniteGraphFreeGroup

/-!
# Fundamental group of a finite connected graph

The graph is a finite directed multigraph represented as a Mathlib `Quiver`.
Its geometric realization has one interval cell for each edge, with the
endpoints attached to the corresponding vertices. Connectivity is imposed
after symmetrizing the edges, so orientations and parallel edges are retained.

The challenge asks for the standard topological statement: the fundamental
group of this finite connected graph is free of rank `E - V + 1`.
-/

class FiniteQuiver (V : Type u) [Quiver.{u} V] where
  finite_hom : ∀ a b : V, Fintype (@Quiver.Hom V _ a b)

@[reducible]
instance finiteHom {V : Type u} [Quiver.{u} V] [FiniteQuiver V] (a b : V) :
    Fintype (@Quiver.Hom V _ a b) :=
  FiniteQuiver.finite_hom (V := V) a b

/-- Connectivity of the underlying undirected multigraph. -/
class WeaklyConnected (V : Type u) [Quiver.{u} V] : Prop where
  path : ∀ a b : V,
    Nonempty (@Path (Symmetrify V) (Quiver.symmetrifyQuiver V) a b)

def baseTotalEquiv (V : Type u) [Quiver.{u} V] :
    Quiver.Total V ≃ Σ a : V, Σ b : V, a ⟶ b where
  toFun e := ⟨e.left, e.right, e.hom⟩
  invFun e := ⟨e.1, e.2.1, e.2.2⟩
  left_inv e := by cases e; rfl
  right_inv e := by cases e; rfl

noncomputable instance baseTotalFintypeInst [Fintype V] [Quiver.{u} V]
    [∀ a b : V, Fintype (a ⟶ b)] : Fintype (Quiver.Total V) := by
  classical
  exact Fintype.ofEquiv _ (baseTotalEquiv V).symm

/-- The number of vertices. -/
def vertexCount {V : Type u} [Fintype V] : ℕ := Fintype.card V

/-- The number of directed edges, counted with multiplicity. -/
def edgeCount {V : Type u} [Quiver.{u} V] [Fintype V] [FiniteQuiver V] : ℕ :=
  Fintype.card (Quiver.Total V)

/- The natural-number cycle rank used by the solution. -/
abbrev cycleRank {V : Type u} [Quiver.{u} V] [Fintype V] [FiniteQuiver V] : ℕ :=
  edgeCount (V := V) + 1 - vertexCount (V := V)

/-- The combinatorial fundamental group based at `root`. -/
abbrev graphFundamentalGroup {V : Type u} [Quiver.{u} V] (root : V) :=
  End ((Quiver.FreeGroupoid.of V).obj root)

/-- Vertices in the path-lifting cover over a root. -/
abbrev graphCoverVertex {V : Type u} [Quiver.{u} V] (root : V) :=
  Σ v : V, ((Quiver.FreeGroupoid.of V).obj root ⟶
    (Quiver.FreeGroupoid.of V).obj v)

instance graphCoverQuiver {V : Type u} [Quiver.{u} V] (root : V) :
    Quiver (graphCoverVertex root) where
  Hom x y := {e : x.1 ⟶ y.1 //
    x.2 ≫ (Quiver.FreeGroupoid.of V).map e = y.2}

/-- The path-lifting projection to the original quiver. -/
def graphCoverProjection {V : Type u} [Quiver.{u} V] (root : V) :
    graphCoverVertex root ⥤q V where
  obj x := x.1
  map e := e.1

/-- The disjoint union of discrete vertices and one interval for each edge. -/
abbrev graphRealizationPre (V : Type u) [Quiver.{u} V] :=
  WithDiscreteTopology V ⊕
    Σ _e : WithDiscreteTopology (Quiver.Total V), I

abbrev graphDiscreteVertex {V : Type u} (v : V) : WithDiscreteTopology V :=
  WithTopology.toTopology (⊥ : TopologicalSpace V) v

abbrev graphDiscreteEdge {V : Type u} [Quiver.{u} V] (e : Quiver.Total V) :
    WithDiscreteTopology (Quiver.Total V) :=
  WithTopology.toTopology (⊥ : TopologicalSpace (Quiver.Total V)) e

abbrev graphVertexUnderlying {V : Type u} (v : WithDiscreteTopology V) : V :=
  WithTopology.ofTopology v

abbrev graphEdgeUnderlying {V : Type u} [Quiver.{u} V]
    (e : WithDiscreteTopology (Quiver.Total V)) : Quiver.Total V :=
  WithTopology.ofTopology e

/-- The endpoint identifications used to form the geometric realization. -/
inductive graphRealizationGenerator {V : Type u} [Quiver.{u} V] :
    graphRealizationPre V → graphRealizationPre V → Prop
  | source (e : Quiver.Total V) :
      graphRealizationGenerator
        (Sum.inr ⟨graphDiscreteEdge e, 0⟩) (Sum.inl (graphDiscreteVertex e.left))
  | target (e : Quiver.Total V) :
      graphRealizationGenerator
        (Sum.inr ⟨graphDiscreteEdge e, 1⟩) (Sum.inl (graphDiscreteVertex e.right))

/-- The equivalence relation generated by the two endpoint identifications. -/
instance graphRealizationSetoid {V : Type u} [Quiver.{u} V] :
    Setoid (graphRealizationPre V) :=
  Relation.EqvGen.setoid (graphRealizationGenerator (V := V))

/-- The geometric realization of a finite directed multigraph. -/
abbrev graphRealization (V : Type u) [Quiver.{u} V] :=
  Quotient (graphRealizationSetoid (V := V))

/-- The quotient map from the disjoint union of cells. -/
abbrev graphRealizationQuotient {V : Type u} [Quiver.{u} V] :
    graphRealizationPre V → graphRealization V :=
  Quotient.mk'

/-- The point of the realization corresponding to a vertex. -/
def graphVertex {V : Type u} [Quiver.{u} V] (v : V) : graphRealization V :=
  graphRealizationQuotient (Sum.inl (graphDiscreteVertex v))

/-
The topological free-group statement is deliberately left as the small
Comparator-facing challenge hole. Its proved counterpart is in `Solution.lean`.
-/
theorem graph_fundamental_group_free_rank {V : Type u} [Quiver.{u} V]
    [Fintype V] [FiniteQuiver V] [WeaklyConnected V] (root : V) :
    Nonempty (FundamentalGroup (graphRealization V) (graphVertex root) ≃*
      FreeGroup (Fin (edgeCount (V := V) + 1 - vertexCount (V := V)))) := by
  sorry

end FiniteGraphFreeGroup
