import Mathlib.AlgebraicTopology.FundamentalGroupoid.FundamentalGroup
import Mathlib.AlgebraicTopology.FundamentalGroupoid.InducedMaps
import Mathlib.Topology.Connected.PathConnected
import Mathlib.Topology.Constructions
import Mathlib.Topology.Order
import FiniteGraphFreeGroup.Proof

open Set Function
open CategoryTheory CategoryTheory.SingleObj Quiver
open unitInterval

noncomputable section

universe u

namespace FiniteGraphFreeGroup

/-!
# A geometric realization of a finite quiver

The combinatorial development works with a quiver and its free groupoid.  The
construction in this file supplies the missing topological object: every
directed edge gets a copy of the unit interval, and its two endpoints are
identified with the source and target vertices.  Parallel edges and loops are
kept as distinct interval cells.

The quotient topology is the standard weak topology on this finite one-
dimensional cell complex.  The fundamental-group comparison is developed in
the later lemmas; the definitions here are intentionally independent of any
choice of spanning tree.
-/

/-- The disjoint union of discrete vertices and one interval for each edge. -/
abbrev graphRealizationPre (V : Type u) [Quiver.{u} V] :=
  WithDiscreteTopology V ⊕
    Σ _e : WithDiscreteTopology (Quiver.Total V), I

abbrev graphDiscreteVertex {V : Type u} (v : V) : WithDiscreteTopology V :=
  WithTopology.toTopology (⊥ : TopologicalSpace V) v

abbrev graphDiscreteEdge {V : Type u} [Quiver.{u} V] (e : Quiver.Total V) :
    WithDiscreteTopology (Quiver.Total V) :=
  WithTopology.toTopology (⊥ : TopologicalSpace (Quiver.Total V)) e

abbrev graphVertexUnderlying {V : Type u} (v : WithDiscreteTopology V) : V :=
  WithTopology.ofTopology v

abbrev graphEdgeUnderlying {V : Type u} [Quiver.{u} V]
    (e : WithDiscreteTopology (Quiver.Total V)) : Quiver.Total V :=
  WithTopology.ofTopology e

/-- The endpoint identifications used to form the geometric realization. -/
inductive graphRealizationGenerator {V : Type u} [Quiver.{u} V] :
    graphRealizationPre V → graphRealizationPre V → Prop
  | source (e : Quiver.Total V) :
      graphRealizationGenerator
        (Sum.inr ⟨graphDiscreteEdge e, 0⟩) (Sum.inl (graphDiscreteVertex e.left))
  | target (e : Quiver.Total V) :
      graphRealizationGenerator
        (Sum.inr ⟨graphDiscreteEdge e, 1⟩) (Sum.inl (graphDiscreteVertex e.right))

/-- The equivalence relation generated by the two endpoint identifications. -/
instance graphRealizationSetoid {V : Type u} [Quiver.{u} V] :
    Setoid (graphRealizationPre V) :=
  Relation.EqvGen.setoid (graphRealizationGenerator (V := V))

/-! The endpoint label is an invariant of the quotient relation.  Besides
    separating vertices, this records why no edge cell is accidentally glued
    to a vertex away from its two prescribed endpoints. -/

def graphRealizationEndpointLabel {V : Type u} [Quiver.{u} V]
    : graphRealizationPre V → Option V
  | Sum.inl v => some (graphVertexUnderlying v)
  | Sum.inr ⟨e, t⟩ =>
      if t = 0 then some (graphEdgeUnderlying e).left
      else if t = 1 then some (graphEdgeUnderlying e).right
      else none

lemma graphRealizationGenerator_endpointLabel {V : Type u} [Quiver.{u} V]
    {x y : graphRealizationPre V}
    (h : graphRealizationGenerator x y) :
  graphRealizationEndpointLabel x = graphRealizationEndpointLabel y := by
  cases h <;> simp [graphRealizationEndpointLabel, graphVertexUnderlying,
    graphEdgeUnderlying]

lemma graphRealization_eqvGen_endpointLabel {V : Type u} [Quiver.{u} V]
    {x y : graphRealizationPre V}
    (h : Relation.EqvGen (graphRealizationGenerator (V := V)) x y) :
    graphRealizationEndpointLabel x = graphRealizationEndpointLabel y := by
  induction h with
  | rel x y h => exact graphRealizationGenerator_endpointLabel h
  | refl x => rfl
  | symm x y h ih => exact ih.symm
  | trans x y z hxy hyz ihxy ihyz => exact ihxy.trans ihyz

/-- The geometric realization of a finite directed multigraph. -/
abbrev graphRealization (V : Type u) [Quiver.{u} V] :=
  Quotient (graphRealizationSetoid (V := V))

/-- The quotient map from the disjoint union of cells. -/
abbrev graphRealizationQuotient {V : Type u} [Quiver.{u} V] :
    graphRealizationPre V → graphRealization V :=
  Quotient.mk'

/-- The point of the realization corresponding to a vertex. -/
def graphVertex {V : Type u} [Quiver.{u} V] (v : V) : graphRealization V :=
  graphRealizationQuotient (Sum.inl (graphDiscreteVertex v))

/-- The endpoint label descends to the quotient as a set-theoretic invariant. -/
def graphRealizationEndpointLabelQuotient {V : Type u} [Quiver.{u} V] :
    graphRealization V → Option V :=
  Quotient.lift graphRealizationEndpointLabel
    (fun _ _ h => graphRealization_eqvGen_endpointLabel h)

@[simp]
theorem graphRealizationEndpointLabelQuotient_mk {V : Type u} [Quiver.{u} V]
    (x : graphRealizationPre V) :
    graphRealizationEndpointLabelQuotient (graphRealizationQuotient x) =
      graphRealizationEndpointLabel x := rfl

@[simp]
theorem graphRealizationEndpointLabelQuotient_vertex {V : Type u} [Quiver.{u} V]
    (v : V) :
    graphRealizationEndpointLabelQuotient (graphVertex v) = some v := by
  rfl

/-- The characteristic path of the interval cell associated to an edge. -/
def graphEdgePath {V : Type u} [Quiver.{u} V] (e : Quiver.Total V) :
    C(I, graphRealization V) where
  toFun t := graphRealizationQuotient (Sum.inr ⟨graphDiscreteEdge e, t⟩)
  continuous_toFun :=
    continuous_quotient_mk'.comp <|
      continuous_inr.comp
        (continuous_sigmaMk (i := graphDiscreteEdge e))

@[simp]
theorem graphRealizationQuotient_vertex {V : Type u} [Quiver.{u} V] (v : V) :
    graphRealizationQuotient (Sum.inl (graphDiscreteVertex v)) = graphVertex v := rfl

@[simp]
theorem graphEdgePath_zero {V : Type u} [Quiver.{u} V] (e : Quiver.Total V) :
    graphEdgePath e 0 = graphVertex e.left := by
  exact Quotient.sound (Relation.EqvGen.rel _ _ (graphRealizationGenerator.source e))

@[simp]
theorem graphEdgePath_one {V : Type u} [Quiver.{u} V] (e : Quiver.Total V) :
    graphEdgePath e 1 = graphVertex e.right := by
  exact Quotient.sound (Relation.EqvGen.rel _ _ (graphRealizationGenerator.target e))

theorem graphRealization_edge_interior_ne_vertex {V : Type u} [Quiver.{u} V]
    (e : Quiver.Total V) {t : I} (ht0 : t ≠ 0) (ht1 : t ≠ 1) (v : V) :
    graphRealizationQuotient (Sum.inr ⟨graphDiscreteEdge e, t⟩) ≠ graphVertex v := by
  intro h
  have hlabel := congrArg graphRealizationEndpointLabelQuotient h
  simp [graphRealizationEndpointLabelQuotient_mk,
    graphRealizationEndpointLabel, ht0, ht1] at hlabel

theorem continuous_graphEdgePath {V : Type u} [Quiver.{u} V] (e : Quiver.Total V) :
    Continuous (graphEdgePath e) :=
  (graphEdgePath e).continuous

/-- The interval cell, regarded as a path from the source to the target. -/
def graphRealizationForwardPath {V : Type u} [Quiver.{u} V]
    {a b : V} (e : a ⟶ b) :
    Path (graphVertex a) (graphVertex b) where
  toContinuousMap := graphEdgePath ⟨a, b, e⟩
  source' := graphEdgePath_zero ⟨a, b, e⟩
  target' := graphEdgePath_one ⟨a, b, e⟩

/-- A continuous parametrisation of the part of an interval cell from `t` to
    its source endpoint. -/
def graphEdgeRetraction (t : I) : C(I, I) where
  toFun s :=
    ⟨(1 - (s : ℝ)) * (t : ℝ),
      unitInterval.mul_mem
        ⟨unitInterval.one_minus_nonneg s, unitInterval.one_minus_le_one s⟩ t.2⟩
  continuous_toFun := by fun_prop

@[simp]
theorem graphEdgeRetraction_zero (t : I) : graphEdgeRetraction t 0 = t := by
  apply Subtype.ext
  simp [graphEdgeRetraction]

@[simp]
theorem graphEdgeRetraction_one (t : I) : graphEdgeRetraction t 1 = 0 := by
  apply Subtype.ext
  simp [graphEdgeRetraction]

def graphEdgePathToSource {V : Type u} [Quiver.{u} V]
    (e : Quiver.Total V) (t : I) :
    Path (graphEdgePath e t) (graphVertex e.left) where
  toContinuousMap := (graphEdgePath e).comp (graphEdgeRetraction t)
  source' := by simp
  target' := by simp

theorem graphRealizationPre_join_vertex {V : Type u} [Quiver.{u} V]
    (x : graphRealizationPre V) :
    ∃ v : V, Joined (graphRealizationQuotient x) (graphVertex v) := by
  cases x with
  | inl v =>
      refine ⟨graphVertexUnderlying v, ?_⟩
      exact ⟨Path.refl _⟩
  | inr z =>
      rcases z with ⟨e, t⟩
      refine ⟨(graphEdgeUnderlying e).left, ?_⟩
      refine ⟨?path⟩
      simpa [graphEdgePath, graphEdgeUnderlying, graphDiscreteEdge] using
        (graphEdgePathToSource (graphEdgeUnderlying e) t)

/-! The symmetrified quiver is the combinatorial source used by the free
    groupoid.  Its positive arrows use the characteristic interval in the
    forward direction, while its negative arrows use the same interval in
    reverse. -/

def graphRealizationSymmetricEdgePath {V : Type u} [Quiver.{u} V]
    {a b : V} (e : (Quiver.symmetrifyQuiver V).Hom a b) :
    Path (graphVertex (V := V) a) (graphVertex (V := V) b) :=
  match e with
  | Sum.inl e => graphRealizationForwardPath e
  | Sum.inr e => (graphRealizationForwardPath e).symm

def graphRealizationQuiverPath {V : Type u} [Quiver.{u} V]
    {a b : V}
    (p : @Quiver.Path (Quiver.Symmetrify V)
      (Quiver.symmetrifyQuiver V) a b) :
    Path (graphVertex (V := V) a) (graphVertex (V := V) b) := by
  induction p with
  | nil => exact Path.refl _
  | cons p e ih => exact ih.trans (graphRealizationSymmetricEdgePath e)

theorem graphRealizationQuiverPath_nil {V : Type u} [Quiver.{u} V]
    (a : V) :
    graphRealizationQuiverPath
      (Quiver.Path.nil : @Quiver.Path (Quiver.Symmetrify V)
        (Quiver.symmetrifyQuiver V) a a) = Path.refl (graphVertex a) := rfl

theorem graphRealization_pathConnected {V : Type u} [Quiver.{u} V]
    [WeaklyConnected V] (root : V) :
    PathConnectedSpace (graphRealization V) where
  nonempty := ⟨graphVertex root⟩
  joined x y := by
    refine Quotient.inductionOn₂ x y ?_
    intro x y
    rcases graphRealizationPre_join_vertex x with ⟨a, hxa⟩
    rcases graphRealizationPre_join_vertex y with ⟨b, hyb⟩
    rcases WeaklyConnected.path a b with ⟨p⟩
    exact ⟨hxa.somePath.trans ((graphRealizationQuiverPath p).trans hyb.somePath.symm)⟩

theorem graphRealization_compact {V : Type u} [Quiver.{u} V]
    [Fintype V] [FiniteQuiver V] : CompactSpace (graphRealization V) := by
  letI : CompactSpace (graphRealizationPre V) := by infer_instance
  infer_instance

def graphRealizationQuiverMap {V : Type u} [Quiver.{u} V] :
    V ⥤q FundamentalGroupoid (graphRealization V) where
  obj v := FundamentalGroupoid.mk (graphVertex v)
  map e := FundamentalGroupoid.fromPath
    (Path.Homotopic.Quotient.mk (graphRealizationForwardPath e))

/-! The universal property of Mathlib's free groupoid produces the canonical
    functor from the combinatorial graph groupoid into the topological
    fundamental groupoid of the realization. -/

def graphFreeGroupoidToTopological {V : Type u} [Quiver.{u} V] :
    Quiver.FreeGroupoid V ⥤ FundamentalGroupoid (graphRealization V) :=
  Quiver.FreeGroupoid.lift (graphRealizationQuiverMap (V := V))

theorem graphFreeGroupoidToTopological_restrict {V : Type u} [Quiver.{u} V] :
    (Quiver.FreeGroupoid.of V ⋙q
      (graphFreeGroupoidToTopological (V := V)).toPrefunctor) =
      graphRealizationQuiverMap (V := V) := by
  exact Quiver.FreeGroupoid.lift_spec (graphRealizationQuiverMap (V := V))

/-! Taking the endomorphism group at a chosen vertex gives the canonical
    comparison homomorphism on fundamental groups.  The present file proves
    its construction and its behavior on edge generators; an isomorphism
    theorem requires the separate topological normal-form argument for paths
    in a finite one-dimensional cell complex. -/

def graphCombinatorialToTopological {V : Type u} [Quiver.{u} V]
    (root : V) :
    graphFundamentalGroup root →*
      FundamentalGroup (graphRealization V) (graphVertex root) :=
  (graphFreeGroupoidToTopological (V := V)).mapEnd _

/-! The geometric basepoint change is available independently of the still
    open comparison-isomorphism theorem. -/

noncomputable def graphTopologicalRootEquiv {V : Type u} [Quiver.{u} V]
    [WeaklyConnected V] (root₁ root₂ : V) :
    FundamentalGroup (graphRealization V) (graphVertex root₁) ≃*
      FundamentalGroup (graphRealization V) (graphVertex root₂) := by
  letI : PathConnectedSpace (graphRealization V) :=
    graphRealization_pathConnected root₁
  exact FundamentalGroup.fundamentalGroupMulEquivOfPathConnected
    (graphVertex root₁) (graphVertex root₂)

theorem graphVertex_injective {V : Type u} [Quiver.{u} V]
    {v w : V} (h : graphVertex v = graphVertex w) : v = w := by
  have h' := Quotient.exact h
  exact Option.some.inj <|
    graphRealization_eqvGen_endpointLabel h'

theorem graphVertex_injective_iff {V : Type u} [Quiver.{u} V]
    {v w : V} : graphVertex v = graphVertex w ↔ v = w := by
  exact ⟨graphVertex_injective, congrArg graphVertex⟩

end FiniteGraphFreeGroup
